force-app/main/default/objects/Unit_System_Record__mdt/Unit_System_Record__mdt.object-meta.xml
<CustomObject>
    <label>Unit System Record</label>
    <pluralLabel>Unit System Records</pluralLabel>
</CustomObject>

force-app/main/default/objects/Unit_System_Record__mdt/fields/Measured_Type__c.field-meta.xml
<CustomField>
    <fullName>Measured_Type__c</fullName>
    <label>Measured Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Length</fullName>
                <default>true</default>
                <label>Length</label>
            </value>
            <value>
                <fullName>Volume</fullName>
            </value>
            <value>
                <fullName>Area</fullName>
            </value>
            <value>
                <fullName>Height</fullName>
            </value>
            <value>
                <fullName>Weight</fullName>
            </value>
            <value>
                <fullName>Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ConversionController.cls
public without sharing class ConversionController {

    @AuraEnabled(cacheable=true)
    public List<pickListValues> getMeasuredType(){

        List<Unit_System_Record__mdt> unitsystemDims =[select Id ,Measured_Type__c, MasterLabel   from Unit_System_Record__mdt];
        for(Unit_System_Record__mdt usDims:unitsystemDims){

        }
        return null;
    }
    public class pickListValues{
        @AuraEnabled
        public String label{get;set;}
        @AuraEnabled
        public String value{get;set;}
    }
}