force-app/main/default/objects/Covid_Test__c/Covid_Test__c.object-meta.xml
<CustomObject>
    <label>Covid Test</label>
    <nameField>
        <displayFormat>C-{000}</displayFormat>
        <label>Covid Test Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Covid Tests</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Covid_Test__c/fields/Case_Reported_Date__c.field-meta.xml
<CustomField>
    <fullName>Case_Reported_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Case Reported Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Covid_Test__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Covid Tests</relationshipLabel>
    <relationshipName>Covid_Tests</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Covid_Test__c/fields/Covid_Positive_Date__c.field-meta.xml
<CustomField>
    <fullName>Covid_Positive_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Covid Positive Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Covid_Test__c/fields/Covid_Tested_Date__c.field-meta.xml
<CustomField>
    <fullName>Covid_Tested_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Covid Tested Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Covid_Test__c/fields/Current_Address__c.field-meta.xml
<CustomField>
    <fullName>Current_Address__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Current Address</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/CovidResponseEmail.cls
global class CovidResponseEmail implements Messaging.InboundEmailHandler {
    
    global Messaging.InboundEmailResult handleInboundEmail(Messaging.inboundEmail email,Messaging.InboundEnvelope env){
                    
      Messaging.InboundEmailResult covidresponseemail = new Messaging.InboundEmailResult();
      String subject= email.subject;
      String body =email.plainTextBody;
      String htmlbody =email.htmlBody;
      String fromAddress = email.fromAddress;
      try {
        Contact tmcontact=[select Id from Contact where Email =:String.escapeSingleQuotes(fromAddress)];
          Covid_Test__c covidTest=new Covid_Test__c();
          covidTest.Contact__c=tmcontact.Id;
       List<String> trrows=HTMLParser.scan(htmlbody);
       System.debug('trrows '+trrows);
       for(String trrow:trrows){
        System.debug('trrows row '+trrow);
        if(trrow.contains('Employee Id') ){
          covidTest.Employee_Id__c=this.matchEmpId(trrow);}
           else if(trrow.contains('Last Visit to Office')){
             covidTest.Last_Visit_to_Office__c=this.matchDate(trrow);}
           else if(trrow.contains('Date of COVID Test')){
             covidTest.Covid_Tested_Date__c=this.matchDate(trrow);}
           else if(trrow.contains('Date Covid Positive Test Result')){
             covidTest.Covid_Positive_Date__c=this.matchDate(trrow);}
            else if(trrow.contains('Date when case was reported')){
            covidTest.Case_Reported_Date__c=this.matchDate(trrow);}
             else if(trrow.contains('Current Address of Employee')){
                   covidTest.Current_Address__c=trrow.substringAfter('Current Address of Employee ');     
                    }
       }
        
			 
     //   List<String> rowList = body.split('\n\n');
     
          
       /*  
       for(String line:rowList){
          
            System.debug('line'+line);
            
            
             covidTest.Contact__c=tmcontact.Id;
             
            if(line.contains('Employee Id') ){
            covidTest.Employee_Id__c=this.matchEmpId(line);}
             else if(line.contains('Last Visit to Office')){
               covidTest.Last_Visit_to_Office__c=this.matchDate(line);}
             else if(line.contains('Date of COVID Test')){
               covidTest.Covid_Tested_Date__c=this.matchDate(line);}
             else if(line.contains('Date Covid Positive Test Result')){
               covidTest.Covid_Positive_Date__c=this.matchDate(line);}
              else if(line.contains('Date when case was reported')){
              covidTest.Case_Reported_Date__c=this.matchDate(line);}
               else if(line.contains('Current Address of Employee')){
                     covidTest.Current_Address__c=line.substringAfter('Current Address of Employee ');     
                      }
                   
              
          
        }*/
        System.debug(covidTest);
         Database.upsert(covidTest);
        covidresponseemail.success=true;
        covidresponseemail.message='Created Covid Response for Contact';
        return null;

    }
    catch (Exception e) {
        System.debug('Incorrect Format Email Exception' + e);
        return null;        
    }

  }
    private String matchEmpId(String line){
       // System.debug('match line'+line);
        Pattern datePattern = Pattern.compile('(\\d+{7})');
        Matcher dateMatcher = datePattern.matcher(line);
        
        if (dateMatcher.find()) {
        System.debug('matcher group'+dateMatcher.group(1));
        return dateMatcher.group(1);
        }
        else{
            return null;
        }
    }
    private Date matchDate(String line){
        Pattern datePattern = Pattern.compile('([0-9]{0,2}/[0-9]{0,2}/[0-9]{4})');
        Matcher dateMatcher = datePattern.matcher(line);
         if(dateMatcher.find()){
         System.debug('matcher group'+dateMatcher.group(1));
        return Date.parse(dateMatcher.group(1));
         }
        else{
            return null;
        }
    }
    private String replaceBreaks(String htmlline){
         Pattern datePattern = Pattern.compile('<br/>');
        Matcher dateMatcher = datePattern.matcher(htmlline);
        return null;
    }
}