force-app/main/default/objects/IT_Slabs__mdt/IT_Slabs__mdt.object-meta.xml
<CustomObject>
    <label>IT Slab</label>
    <pluralLabel>IT Slabs</pluralLabel>
</CustomObject>

force-app/main/default/objects/IT_Slabs__mdt/fields/citizen_type__c.field-meta.xml
<CustomField>
    <fullName>citizen_type__c</fullName>
    <label>citizen type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Mid Level (&lt;60)</fullName>
                <default>true</default>
                <label>Mid Level (&lt;60)</label>
            </value>
            <value>
                <fullName>Senior (60 to 80)</fullName>
            </value>
            <value>
                <fullName>Super Senior (&gt;80)</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/IT_Slabs__mdt/fields/lower_limit_taxable_income__c.field-meta.xml
<CustomField>
    <fullName>lower_limit_taxable_income__c</fullName>
    <label>lower limit taxable income</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IT_Slabs__mdt/fields/net_taxable_income__c.field-meta.xml
<CustomField>
    <fullName>net_taxable_income__c</fullName>
    <label>net taxable income</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IT_Slabs__mdt/fields/tax_constant__c.field-meta.xml
<CustomField>
    <fullName>tax_constant__c</fullName>
    <label>tax constant</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/IT_Slabs__mdt/fields/tax_percent__c.field-meta.xml
<CustomField>
    <fullName>tax_percent__c</fullName>
    <label>tax percent</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Percent</type>
</CustomField>

force-app/main/default/objects/IT_Slabs__mdt/fields/upper_limit__c.field-meta.xml
<CustomField>
    <fullName>upper_limit__c</fullName>
    <label>upper limit</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/monthly_income__c/monthly_income__c.object-meta.xml
<CustomObject>
    <label>monthly income</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>monthly income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>monthly incomes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/monthly_income__c/fields/paydate__c.field-meta.xml
<CustomField>
    <fullName>paydate__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>pay date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/monthly_income__c/fields/taxable_income__c.field-meta.xml
<CustomField>
    <fullName>taxable_income__c</fullName>
    <formula>basic_income__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>taxable income</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/monthly_income__c/fields/year__c.field-meta.xml
<CustomField>
    <fullName>year__c</fullName>
    <label>year</label>
    <referenceTo>yearly_income__c</referenceTo>
    <relationshipLabel>monthly incomes</relationshipLabel>
    <relationshipName>monthly_incomes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/yearly_income__c/yearly_income__c.object-meta.xml
<CustomObject>
    <label>yearly income</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>yearly income Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>yearly incomes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/yearly_income__c/fields/income_tax__c.field-meta.xml
<CustomField>
    <fullName>income_tax__c</fullName>
    <label>income tax</label>
    <precision>9</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/yearly_income__c/fields/taxable_income__c.field-meta.xml
<CustomField>
    <fullName>taxable_income__c</fullName>
    <label>taxable income</label>
    <summarizedField>monthly_income__c.basic_income__c</summarizedField>
    <summaryForeignKey>monthly_income__c.year__c</summaryForeignKey>
    <summaryOperation>sum</summaryOperation>
    <type>Summary</type>
</CustomField>

force-app/main/default/classes/IncomeTaxCalculator.cls
/*
 * 
 *
 * Deduct SD
 * Deduct 1st slab with no tax 
 * Deduct from corresponding slabs lower limit and multiply with tax percent then add with tax constant 
 * 
 * 
 * 
 
*/


public class IncomeTaxCalculator {

    
    public static void afterUpdate(List<monthly_income__c> newValues){
	 
        System.debug(newValues.get(0).taxable_income__c);
               
        List<AggregateResult> yearlyrollup =[select  sum(taxable_income__c) total,year__c from monthly_income__c where  CALENDAR_YEAR(paydate__c) =2019  group by year__c];
        System.debug(yearlyrollup.get(0).get('total'));
         System.debug(yearlyrollup.get(0).get('year__c') +'year record');
        
         Id yearrecord =(Id)yearlyrollup.get(0).get('year__c');
         List<yearly_income__c> yearlyincomes =[select year__c,taxable_income__c,income_tax__c from  yearly_income__c where Id =:yearrecord];

        
        
      //  List<IT_Slabs__mdt> itslabList=[select Id,citizen_type__c ,lower_limit_taxable_income__c,net_taxable_income__c,upper_limit__c,tax_constant__c,tax_percent__c from IT_Slabs__mdt];
        Map<String,IT_Slabs__mdt> itslabMap = new Map<String,IT_Slabs__mdt>([select Id,citizen_type__c ,net_taxable_income__c ,lower_limit_taxable_income__c,upper_limit__c,tax_constant__c,tax_percent__c from IT_Slabs__mdt]);
        System.debug(itslabMap.keySet());
        Double taxableamount =(Double)(yearlyrollup.get(0).get('total'));
      /*  for(IT_Slabs__mdt itslabmdt:itslabMap.values()){
        
            if(itslabmdt.tax_percent__c ==0){
                taxableamount = (taxableamount - itslabmdt.net_taxable_income__c)-50000;
                
            }
            
            
        }*/
        Double taxamount =0;
          for(IT_Slabs__mdt itslabmdt:itslabMap.values()){
        
              if(itslabmdt.lower_limit_taxable_income__c <= taxableamount && taxableamount <=itslabmdt.upper_limit__c){
				
					taxamount =   (taxableamount -   itslabmdt.lower_limit_taxable_income__c)  * (itslabmdt.tax_percent__c/100) ;
                  	taxamount =taxamount+itslabmdt.tax_constant__c;
                  yearlyincomes.get(0).income_tax__c =taxamount;
              }
            
            
        }
        update yearlyincomes;
        System.debug('update in yearly taxes'+taxamount);
        
        
    }
}