force-app/main/default/objects/Batch_Controls__mdt/Batch_Controls__mdt.object-meta.xml
<CustomObject>
    <description>Batch Controls through Trigger Settings</description>
    <label>Batch Control</label>
    <pluralLabel>Batch Controls</pluralLabel>
</CustomObject>

force-app/main/default/objects/Batch_Controls__mdt/fields/Business_Classes__c.field-meta.xml
<CustomField>
    <fullName>Business_Classes__c</fullName>
    <inlineHelpText>business Classes to be passed in a semicolon</inlineHelpText>
    <label>Business Classes</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/Batch_Controls__mdt/fields/SObjectType__c.field-meta.xml
<CustomField>
    <fullName>SObjectType__c</fullName>
    <label>SObjectType</label>
    <length>30</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_By_Pass_Setting__mdt/Trigger_By_Pass_Setting__mdt.object-meta.xml
<CustomObject>
    <label>Trigger By Pass Setting</label>
    <pluralLabel>Trigger By Pass Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/Trigger_By_Pass_Setting__mdt/fields/Profile__c.field-meta.xml
<CustomField>
    <fullName>Profile__c</fullName>
    <label>Profile</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_By_Pass_Setting__mdt/fields/Trigger_Setting__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Setting__c</fullName>
    <label>Trigger Setting</label>
    <referenceTo>Trigger_Setting__mdt</referenceTo>
    <relationshipLabel>Trigger By Pass Settings</relationshipLabel>
    <relationshipName>Trigger_By_Pass_Settings</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Trigger_By_Pass_Setting__mdt/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterDelete__c.field-meta.xml
<CustomField>
    <fullName>afterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>afterDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterInsert__c.field-meta.xml
<CustomField>
    <fullName>afterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>afterInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterUndelete__c.field-meta.xml
<CustomField>
    <fullName>afterUndelete__c</fullName>
    <defaultValue>true</defaultValue>
    <label>afterUndelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterUpdate__c.field-meta.xml
<CustomField>
    <fullName>afterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>afterUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/beforeDelete__c.field-meta.xml
<CustomField>
    <fullName>beforeDelete__c</fullName>
    <defaultValue>true</defaultValue>
    <label>beforeDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/beforeInsert__c.field-meta.xml
<CustomField>
    <fullName>beforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>beforeInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/beforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>beforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>beforeUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/SObject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Api_Name__c</fullName>
    <label>SObject Api Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerDispatcher.cls
public class TriggerDispatcher {
    public static void run(ITriggerHandler handler){
        
        
        
        //Check if the trigger is disabled
        /*if (handler.IsDisabled()){
return;
}*/
        String triggerName= getSObjectName();
        Map<String,Trigger_Setting__mdt> triggerSettingMap =  initTriggerSettingMap(triggerName);
        //Get the trigger active information from custom settings by trigger name
        //  Boolean isActive = true;//TriggerSetting__c.getValues(triggerName).isActive__c;
        /*  if(!triggerSettingMap.isEmpty() && triggerSettingMap.get(triggerName).isDisabled__c){ 

return;
}*/
        TriggerParameters triggerParameters=new TriggerParameters();
        if(triggerSettingMap.size()>0 && !triggerSettingMap.get(triggerName).isDisabled__c){
            
            switch on Trigger.operationType{
                
                when BEFORE_INSERT {
                    //create related records
                    
                    if(triggerSettingMap.get(triggerName).beforeInsert__c &&  !(disableBatch()) ){
                        handler.beforeInsert(trigger.new);
                    }
                }
                when AFTER_INSERT {
                    //create related records
                    if(triggerSettingMap.get(triggerName).afterInsert__c  &&  !(disableBatch()) ){
                        handler.afterInsert(trigger.new, trigger.newMap);
                    }
                }
                when BEFORE_UPDATE {
                    //create related records
                    if(triggerSettingMap.get(triggerName).beforeUpdate__c  &&  !(disableBatch())  ){
                        handler.beforeUpdate(trigger.new, trigger.newMap, trigger.old, trigger.oldMap);
                    }
                }
                when AFTER_UPDATE {
                    //create related records
                    if(triggerSettingMap.get(triggerName).afterUpdate__c  &&  !(disableBatch())  ){
                        handler.afterUpdate(trigger.new, trigger.newMap, trigger.old, trigger.oldMap);
                        
                    }
                }
                when BEFORE_DELETE {
                    //create related records
                    if(triggerSettingMap.get(triggerName).beforeDelete__c  &&  !(disableBatch())  ){
                        handler.beforeDelete(trigger.old, trigger.oldMap);
                        
                    }
                    
                }
                when AFTER_DELETE {
                    //create related records
                    if(triggerSettingMap.get(triggerName).afterDelete__c  &&  !(disableBatch())  ){
                        handler.afterDelete(trigger.old, trigger.oldMap);
                        
                    }
                }
                
                when AFTER_UNDELETE {
                    //do nothing for AFTER_UNDELETE, BEFORE_DELETE, or BEFORE_UPDATE
                    if(triggerSettingMap.get(triggerName).afterUndelete__c  &&  !(disableBatch())  ){
                        handler.afterUnDelete(trigger.new, trigger.newMap);
                    }
                }
            }
        } 
        
    }
    
    public static Map<String,Trigger_Setting__mdt> initTriggerSettingMap(String sObjectApi){
        List<Trigger_Setting__mdt>  triggerSettingRecords=[select Id,SObject_Api_Name__c,MasterLabel ,(select MasterLabel,UserId__c,Profile__c from Trigger_By_Pass_Settings__r),isDisabled__c,afterInsert__c,afterUpdate__c,beforeInsert__c,beforeUpdate__c,afterDelete__c,beforeDelete__c,afterUndelete__c from Trigger_Setting__mdt where SObject_Api_Name__c =:sObjectApi];
        Map<String,Trigger_Setting__mdt> triggerSettingMap = new Map<String,Trigger_Setting__mdt>();
        for(Trigger_Setting__mdt triggerSetting :triggerSettingRecords ){
            
            triggerSettingMap.put(triggerSetting.SObject_Api_Name__c,triggerSetting);
            
        }
        return triggerSettingMap;
    }
    
    public static boolean disableBatch(){
   
        String sObjectname=getSObjectName();
        List<Batch_Controls__mdt> batchControlList =[select MasterLabel,SObjectType__c,DeveloperName,After_Delete__c,After_Insert__c,After_Update__c,Before_Delete__c,Before_Insert__c, Before_Update__c,Business_Classes__c  from Batch_Controls__mdt where SObjectType__c=:sObjectname];
        if(batchControlList.size()>0){
            
            
            boolean disabledflg=(batchControlList.get(0).Before_Insert__c || batchControlList.get(0).Before_Update__c || batchControlList.get(0).After_Update__c || batchControlList.get(0).After_Insert__c || batchControlList.get(0).After_Delete__c );
            System.debug('disable batch class'+disabledflg);
            return (System.isBatch() &&  disabledflg);
        }
        else 
        {  return false;}
    }
    
    public static String getSObjectName(){
        SObjectType triggerObjType;
        if(Trigger.isDelete || Trigger.isUndelete){
            triggerObjType  = trigger.old.getSObjectType();
        }
        triggerObjType  = trigger.new.getSObjectType();
        return triggerObjType.getDescribe().getName() ;
    }
}