force-app/main/default/objects/Campsite__c/Campsite__c.object-meta.xml
<CustomObject>
    <label>Campsite</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campsite Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campsites</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Campsite_Reservation__c/Campsite_Reservation__c.object-meta.xml
<CustomObject>
    <label>Campsite Reservation</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Campsitereservation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Campsite_Reservations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Campsite_Reservation__c/fields/Campsite__c.field-meta.xml
<CustomField>
    <fullName>Campsite__c</fullName>
    <label>Campsite</label>
    <referenceTo>Campsite__c</referenceTo>
    <relationshipLabel>Campsite_Reservation</relationshipLabel>
    <relationshipName>Campsite_Reservations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/RecordFormCustomUI.cls
public class RecordFormCustomUI {

    @AuraEnabled
    public static Map<String,String> getcampsites(String campsite)
    {
        Map<String,String> exampMap = new Map<String,String>();
        exampMap.put('key1','value1');
        exampMap.put('key2','value1');
        exampMap.put('key3','value1');
        List<Campsite__c> campsites= [select Id,Name,(select Name,Id,User__c From Campsite_Reservations__r) from Campsite__c where Id=:campsite	];
        return exampMap;
    }
}