force-app/main/default/objects/ESB_Inbound_Queue__c/ESB_Inbound_Queue__c.object-meta.xml
<CustomObject>
    <label>ESB Inbound Queue</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ESB Inbound Queue Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ESB Inbound Queues</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ESB_Inbound_Queue__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Body</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/ESB_Inbound_Queue__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EnqueueBatch.cls
public class EnqueueBatch  implements Database.Batchable<sObject>,Database.Stateful {
	public  List<ESB_Inbound_Queue__c> processedQueueList= new List<ESB_Inbound_Queue__c>();
    public  Database.QueryLocator start(Database.BatchableContext bc){
       
        return Database.getQueryLocator([select Id,Body__c,Status__c from ESB_Inbound_Queue__c where Status__c='Pending']);
    }
    public  void execute(Database.BatchableContext bc,List<ESB_Inbound_Queue__c> queueRecords){
       
        for(ESB_Inbound_Queue__c inboundqueue:queueRecords){
            
            
            inboundqueue.Status__c='Completed';
            processedQueueList.add(inboundqueue);
        }
    }
    public void finish(Database.BatchableContext bc)
    {
        
        Database.update(processedQueueList);
        System.debug(bc.getJobId()+'batch job id');
       
    }
          
}