force-app/main/default/objects/Daily_Expenses__c/Daily_Expenses__c.object-meta.xml
<CustomObject>
    <label>Daily Expense</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Daily Expenses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Expenses__c/fields/Bill_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_Amount__c</fullName>
    <label>Bill Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Expenses__c/fields/Bill_Date__c.field-meta.xml
<CustomField>
    <fullName>Bill_Date__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Bill Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Daily_Expenses__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <label>Current Month Expense</label>
    <referenceTo>Monthly_Expense__c</referenceTo>
    <relationshipLabel>Daily Expenses</relationshipLabel>
    <relationshipName>Daily_Expenses_for_Month</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Expenses__c/fields/Expense_Type__c.field-meta.xml
<CustomField>
    <fullName>Expense_Type__c</fullName>
    <label>Expense Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Domestic</fullName>
            </value>
            <value>
                <fullName>Mobile and BroadBand</fullName>
            </value>
            <value>
                <fullName>Travel</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Clothing</fullName>
            </value>
            <value>
                <fullName>Health</fullName>
            </value>
            <value>
                <fullName>Credit Card Liability</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Daily_Expenses__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>Current_Month__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_table_Columns__c/Data_table_Columns__c.object-meta.xml
<CustomObject>
    <label>Data Table Column</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Data table Columns Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Data Table Columns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Data_table_Columns__c/fields/editable__c.field-meta.xml
<CustomField>
    <fullName>editable__c</fullName>
    <defaultValue>false</defaultValue>
    <label>editable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Data_table_Columns__c/fields/fieldName__c.field-meta.xml
<CustomField>
    <fullName>fieldName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>fieldName</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_table_Columns__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Data_table_Columns__c/fields/type__c.field-meta.xml
<CustomField>
    <fullName>type__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>type</label>
    <length>10</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Monthly_Expense__c/Monthly_Expense__c.object-meta.xml
<CustomObject>
    <label>Monthly Expense</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Monthly Expense Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Monthly Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Monthly_Expense__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>CASE( MONTH(DATEVALUE( CreatedDate)),01,&apos;JAN&apos;,02,&apos;FEB&apos;,03,&apos;MAR&apos;,04,&apos;APR&apos;,05,&apos;MAY&apos;,06,&apos;JUN&apos;,07,&apos;JUL&apos;,08,&apos;AUG&apos;,09,&apos;SEP&apos;,10,&apos;OCT&apos;,11,&apos;NOV&apos;,12,&apos;DEC&apos;,&apos;UNK&apos;)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Row_Actions__c/Row_Actions__c.object-meta.xml
<CustomObject>
    <label>Row Action</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Row Actions Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Row Actions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Row_Actions__c/fields/label__c.field-meta.xml
<CustomField>
    <fullName>label__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>label</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExpenseController.cls
public with sharing class ExpenseController {


    @AuraEnabled(cacheable=true)
    public static DTable getDailyExpenses(String month){
       
        DTable dtable = new DTable();
        List<DTColumns> dtcols= new List<DTColumns>();
        dtable.dtcols = new List<DTColumns>();
        for(Data_table_Columns__c dtcol:[select fieldName__c,  editable__c, label__c,type__c  from Data_table_Columns__c order by fieldName__c desc]){

            DTColumns dtc2=new DTColumns();
            dtc2.label=dtcol.label__c;
            dtc2.fieldName=dtcol.fieldName__c;
            dtc2.editable=dtcol.editable__c;
            dtc2.type=dtcol.type__c;
            dtable.dtcols.add(dtc2);
        }
 
        
        dtable.dailyExpenses=[select Id,Bill_Amount__c,Month__c,Bill_Date__c,Current_Month__c,Name,Current_Month__r.Month__c,Expense_Type__c from Daily_Expenses__c];
        return dtable;
    }

    @AuraEnabled(cacheable=true)
    public static List<Row_Actions__c> getRowActions(){
        return [select Name,label__c from Row_Actions__c order by Name  desc];
    }
    public class DTable{

        @AuraEnabled
        public List<Daily_Expenses__c> dailyExpenses;
        @AuraEnabled
        public List<DTColumns> dtcols;
    }
    public class DTResponseData{

    }
    public Class DTColumns{
    

        @AuraEnabled
        public String label;
        @AuraEnabled
        public String fieldName;
        @AuraEnabled
        public Boolean editable;
        @AuraEnabled
        public String type; 
       
     }
}