force-app/main/default/objects/Daily_Expenses__c/Daily_Expenses__c.object-meta.xml
<CustomObject>
    <label>Daily Expense</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Daily Expenses Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Daily Expenses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Daily_Expenses__c/fields/Bill_Amount__c.field-meta.xml
<CustomField>
    <fullName>Bill_Amount__c</fullName>
    <label>Bill Amount</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Daily_Expenses__c/fields/Current_Month__c.field-meta.xml
<CustomField>
    <fullName>Current_Month__c</fullName>
    <label>Current Month Expense</label>
    <referenceTo>Monthly_Expense__c</referenceTo>
    <relationshipLabel>Daily Expenses</relationshipLabel>
    <relationshipName>Daily_Expenses_for_Month</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Daily_Expenses__c/fields/Month__c.field-meta.xml
<CustomField>
    <fullName>Month__c</fullName>
    <formula>Current_Month__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Month</label>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ExpenseCmpDaoController.cls
public with sharing class ExpenseCmpDaoController {
    public ExpenseCmpDaoController() {

    }

    @AuraEnabled
    public static Daily_Expenses__c getExpenses(Id recordId){
        try {

            Daily_Expenses__c de=[select Current_Month__c,Id,Bill_Amount__c,Month__c from Daily_Expenses__c where id =: recordId];
            return de;
            
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }
}