force-app/main/default/objects/ChatBot__c/ChatBot__c.object-meta.xml
<CustomObject>
    <label>ChatBot</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>ChatBot Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>ChatBot</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/ChatBot__c/fields/Apex_Class__c.field-meta.xml
<CustomField>
    <fullName>Apex_Class__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Apex Class</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/ChatBot__c/fields/Pattern__c.field-meta.xml
<CustomField>
    <fullName>Pattern__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>Pattern</label>
    <length>250</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BotController.cls
public class BotController {
    
     class HandlerMapping
    {
   		public String handlerClassName;
        public Pattern utterancePattern;

        public HandlerMapping(String handlerClassName, String patternStr) {
            this.handlerClassName = handlerClassName;
            this.utterancePattern = Pattern.compile(patternStr);
        }
    }
    static List<HandlerMapping> handlemappings;
    static 
    {
        List<ChatBot__c> commands =[select Apex_Class__c,Pattern__c from ChatBot__c];
        System.debug(commands);
        List<HandlerMapping> mappings = new List<HandlerMapping>();
        for(ChatBot__c command :commands)
        {
           mappings.add(new HandlerMapping(command.Apex_Class__c,command.Pattern__c));
        }
        handlemappings=mappings;
    }
    @AuraEnabled
    public static  BotMessage  submit(String utterance)
    {
        try
        {
        for(HandlerMapping mapcommands:BotController.handlemappings)
        {
            	System.debug(utterance+'pattern' +mapcommands.utterancePattern);
             	Matcher utteranceMatcher = mapcommands.utterancePattern.matcher(utterance);
                if (utteranceMatcher.matches()) {
                    Type t = Type.forName('', mapcommands.handlerClassName);
                    BotHandler h = (BotHandler)t.newInstance();
                    return h.handle(utterance);
         		 }
          }
        return new  BotMessage('Bot','I cannot help ');
        }
    
        catch(Exception e){System.debug(' Exception e'+e); return new  BotMessage('Bot','OH!!!Something went wrong ');}}
	}