force-app/main/default/objects/Category__c/Category__c.object-meta.xml
<CustomObject>
    <description>Category of books</description>
    <label>Category</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Category Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hospital__c/Hospital__c.object-meta.xml
<CustomObject>
    <label>Hospital</label>
    <nameField>
        <displayFormat>HSP-{0000}</displayFormat>
        <label>Hospitals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Hospitals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Hospital__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Super Speciality</fullName>
            </value>
            <value>
                <fullName>Multi Speciality</fullName>
            </value>
            <value>
                <fullName>Clinic</fullName>
            </value>
            <value>
                <fullName>Speciality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Hospital__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>City</label>
    <referenceTo>Location__c</referenceTo>
    <relationshipLabel>Hospitals</relationshipLabel>
    <relationshipName>Hospitals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Hospital__c/fields/HospitalName__c.field-meta.xml
<CustomField>
    <fullName>HospitalName__c</fullName>
    <encryptionScheme>None</encryptionScheme>
    <label>HospitalName</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Location__c/Location__c.object-meta.xml
<CustomObject>
    <label>Location</label>
    <nameField>
        <encryptionScheme>None</encryptionScheme>
        <label>Location Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Locations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/HospitalController.cls
public with sharing class HospitalController {

    @AuraEnabled
    public static List<Hospital__c> getallHospital()
    {
        
		      
        return  [select HospitalName__c,Category__c ,City__r.Name,City__r.Phone__c,City__r.Address__c from Hospital__c];
        
    }
    @AuraEnabled
    public static List<Hospital__c> getSuperHosp(String category)
    {
         return  [select HospitalName__c,Category__c ,City__r.Name,City__r.Phone__c,City__r.Address__c from Hospital__c where Category__c =:category];
    }
  
}