force-app/main/default/objects/byPassProfiles__c/byPassProfiles__c.object-meta.xml
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <description>byPassProfiles and Users</description>
    <label>byPassProfiles</label>
</CustomObject>

force-app/main/default/objects/byPassProfiles__c/fields/byPassTrigger__c.field-meta.xml
<CustomField>
    <fullName>byPassTrigger__c</fullName>
    <defaultValue>false</defaultValue>
    <label>byPassTrigger</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterDelete__c.field-meta.xml
<CustomField>
    <fullName>afterDelete__c</fullName>
    <defaultValue>false</defaultValue>
    <label>afterDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterInsert__c.field-meta.xml
<CustomField>
    <fullName>afterInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>afterInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterUndelete__c.field-meta.xml
<CustomField>
    <fullName>afterUndelete__c</fullName>
    <defaultValue>true</defaultValue>
    <label>afterUndelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/afterUpdate__c.field-meta.xml
<CustomField>
    <fullName>afterUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>afterUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/beforeDelete__c.field-meta.xml
<CustomField>
    <fullName>beforeDelete__c</fullName>
    <defaultValue>true</defaultValue>
    <label>beforeDelete</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/beforeInsert__c.field-meta.xml
<CustomField>
    <fullName>beforeInsert__c</fullName>
    <defaultValue>false</defaultValue>
    <label>beforeInsert</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/beforeUpdate__c.field-meta.xml
<CustomField>
    <fullName>beforeUpdate__c</fullName>
    <defaultValue>false</defaultValue>
    <label>beforeUpdate</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Trigger_Setting__mdt/fields/SObject_Api_Name__c.field-meta.xml
<CustomField>
    <fullName>SObject_Api_Name__c</fullName>
    <label>SObject Api Name</label>
    <length>150</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/TriggerDispatcher1.cls
public class TriggerDispatcher1 {
    
    private static Set<String> bypassedHandlers;
    /**
     * Params:Instance of Interface ITriggerHandler1
     * Overload method for various SObject Trigger Handlers to segregate into respective Trigger Events
     * */
    public static void run(ITriggerHandler1 handler){

        String triggerName= getSObjectName();
        Map<String,Trigger_Setting__mdt> triggerSettingMap =  initTriggerSettingMap(triggerName);
        TriggerParameters triggerParameters=new TriggerParameters();
        if((triggerSettingMap.size()==0 )|| (triggerSettingMap.size()>0 && !triggerSettingMap.get(triggerName).isDisabled__c)){
            
            switch on Trigger.operationType{
                
                when BEFORE_INSERT {
                    //Before Insert
                    
                    if(triggerSettingMap.get(triggerName).beforeInsert__c){
                        handler.beforeInsert(triggerParameters);
                    }
                }
                when AFTER_INSERT {
                    //After Insert
                    if(triggerSettingMap.get(triggerName).afterInsert__c){
                        handler.afterInsert(triggerParameters);
                    }
                }
                when BEFORE_UPDATE {
                    //before update
                    if(triggerSettingMap.get(triggerName).beforeUpdate__c){
                        handler.beforeUpdate(triggerParameters);
                    }
                }
                when AFTER_UPDATE {
                    //after update
                    if(triggerSettingMap.get(triggerName).afterUpdate__c){
                        handler.afterUpdate(triggerParameters);
                        
                    }
                }
                when BEFORE_DELETE {
                    //before delete
                    if(triggerSettingMap.get(triggerName).beforeDelete__c){
                        handler.beforeDelete(triggerParameters);
                        
                    }
                    
                }
                when AFTER_DELETE {
                    //after delete
                    if(triggerSettingMap.get(triggerName).afterDelete__c){
                        handler.afterDelete(triggerParameters);
                        
                    }
                }
                
                when AFTER_UNDELETE {
                    //after undelete
                    if(triggerSettingMap.get(triggerName).afterUndelete__c ){
                        handler.afterUnDelete(triggerParameters);
                    }
                }
            }
        } 
        
    }
    /**
     * Prepares Trigger Setting Map  from Custom Metadata
     * */
    public static Map<String,Trigger_Setting__mdt> initTriggerSettingMap(String sObjectApi){
      
        
        
        String soqlquery='select '+System.Label.TFMetadataFields+' from '+System.Label.TFMetadataConfig;
        List<Trigger_Setting__mdt>  triggerSettingRecords=Database.query(soqlquery);
        Map<String,Trigger_Setting__mdt> triggerSettingMap = new Map<String,Trigger_Setting__mdt>();
        for(Trigger_Setting__mdt triggerSetting :triggerSettingRecords ){
            
            triggerSettingMap.put(triggerSetting.SObject_Api_Name__c,triggerSetting);
            
        }
        return triggerSettingMap;
    }
    /**
     * Gets ObjectName from Trigger.new Object Type
     * */
    public static String getSObjectName(){
        SObjectType triggerObjType;
        if(Trigger.isDelete || Trigger.isUndelete){
            triggerObjType  = trigger.old.getSObjectType();
        }
        else
        triggerObjType  = trigger.new.getSObjectType();
        return triggerObjType.getDescribe().getName() ;
    }
    public Boolean isDisabled(){
        
        
        byPassProfiles__c profileCstmSetting = byPassProfiles__c.getInstance(UserInfo.getUserId());
        return profileCstmSetting.byPassTrigger__c;
    }
     
}